version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: timesheet-db-prod
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
    networks:
      - timesheet-network
    restart: unless-stopped

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend.prod
    container_name: timesheet-backend-prod
    environment:
      NODE_ENV: production
      DATABASE_URL: postgresql://${DB_USER}:${DB_PASSWORD}@postgres:5432/${DB_NAME}
      JWT_SECRET: ${JWT_SECRET}
      SESSION_SECRET: ${SESSION_SECRET}
    depends_on:
      - postgres
    networks:
      - timesheet-network
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend.prod
    container_name: timesheet-frontend-prod
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - timesheet-network
    restart: unless-stopped

networks:
  timesheet-network:
    driver: bridge

volumes:
  postgres_data_prod: