version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:16-alpine
    container_name: timesheet-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: timesheet_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d timesheet_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Node.js Application
  app:
    build: .
    container_name: timesheet-app
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/timesheet_db
      JWT_SECRET: dev-jwt-secret
      SESSION_SECRET: dev-session-secret
    ports:
      - "5000:5000"
    volumes:
      - ./client:/app/client
      - ./server:/app/server
      - ./shared:/app/shared
      - ./package.json:/app/package.json
      - ./tsconfig.json:/app/tsconfig.json
      - ./vite.config.ts:/app/vite.config.ts
      - ./drizzle.config.ts:/app/drizzle.config.ts
      - /app/node_modules
    depends_on:
      postgres:
        condition: service_healthy
    command: >
      sh -c "
        echo 'Waiting for database...' &&
        sleep 3 &&
        echo 'Running database setup...' &&
        npm run db:push &&
        echo 'Starting development server...' &&
        npm run dev
      "

volumes:
  postgres_data: